@startuml
@startmindmap
caption Mind map of .Net performance considerations
title Mind map on .Net Web Performance
center header
.Net Web Performance
endheader


* <&flag><b>Performance</b>
** <&globe>Server
*** IIS
**** AppPool config
***** Recycle
***** Idle timeoue
***** Always on
***** Timeouts > 30 s
*** .Net Code
**** ADO.Net
***** [[https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql-server-connection-pooling Connection pooling]]
***** Connection leak
***** Timeouts
****** CommandTimeout
****** ConnectionTimeout
**** ThreadPool Size
**** Caching
***** Metadata Caching
***** Transaction data caching for less time
**** Poor Logic
**** Multiple hops to serve request
*** Database
**** SQL Server
*** I/O
**** File
**** Outbound network
**** Logging overhead
** <&graph>Network
*** [[https://docs.microsoft.com/en-us/windows/client-management/troubleshoot-tcpip-port-exhaust Port exhaustion]]
*** Application / Security Gateway delay
*** Load balancer
**** LB Algorithm
**** Sticky session
*** latency
**** Multiple hops
**** Devices and bandwidth
** <&pulse>Authentication
*** Windows
**** Kerberos missing?
**** Latency to AD

left side

** <&globe>Browser
*** static contents
**** Bundling / Modules
**** Minification
**** Lazy loading
*** Caching
**** JavaScript Caching
***** Angular cache object
**** HttpCaching
***** Expires header
***** cache-control
**** ETag
**** IndexedDB
**** Cache API
*** Requests
**** Compression
***** gzip
**** High payload > 70KB
**** Unwanted
**** Duplicate
**** AJAX
***** No of retries
***** JSON
****** [[https://www.newtonsoft.com/json/help/html/ReducingSerializedJSONSize.htm Attribute size]]
****** Empty values
**** File upload
***** Chunked
***** File Input
**** static
***** Bundling
***** Minification
***** sprite images
*** WebSockets
** <&people>Protocols
*** <s>http 1.1</s> => <&star>Http/2

center footer JoymonOnline

legend right
  Left Side - Browser
  Right Side - Network, infrastructure & servers
  What is not covered
   Desktop & mobile apps connecting to web services
endlegend
@endmindmap
@enduml