@startmindmap
center header
Azure mind maps - Azure SQL
endheader
title Azure - Azure SQL Database(SQL DB) PaaS

* <&flag> Azure SQL
** Elastic pools
*** Moving databases
*** Distributed transactions
**** [[https://docs.microsoft.com/en-us/azure/sql-database/sql-database-elastic-transactions-overview Elastic database transactions]]\nNo MSDTC
***** .Net 4.6.1 onwards
***** Client library not TSQL
***** Cannot work with WCF transactions
left
** Tiers
** Limits
** Feature parity
** HA/DR
caption Azure SQL - Mind Map - Updated on 2020-04-14
center footer JoymonOnline

legend right
  Left Side - Specs, features & theories
  Right Side - Use cases
  
endlegend

@endmindmap