@startuml
@startmindmap
caption Mind map of Windows Networking tools & commands for Developers
title Windows Networking tools & commands for Developers
center header
Windows Networking tools & commands for Developers
endheader
* <&flag><b>Debug</b> \n Networking
** machine configuration
*** hostname
*** whoami
*** getmac
*** ipconfig
*** IIS
**** appcmd

** Authentication
*** <&command>[[https://www.windows-commandline.com/get-sid-of-user/ SiD Utils]]
*** SetSPN
*** Kerberos
**** [[https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/klist klist]]
**** [[https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/ktpass ktpass]]

** Connectivity
*** ping
*** tracert
*** pathping
*** nslookup
*** route
*** <&command>telnet
** <&command>Active
*** arp

*** [[https://docs.microsoft.com/en-us/windows-server/networking/technologies/network-subsystem/net-sub-performance-counters Perfmon]]
*** netstat
*** nbtstat
*** <&file>[[https://docs.microsoft.com/en-us/sysinternals/downloads/tcpview TCPView]]
*** <&command>TCPDump
*** <&command>[[https://blogs.technet.microsoft.com/netmon/2009/05/13/event-tracing-for-windows-and-network-monitor/ logman]]
*** <&command>netsh

left
** <&file>Logging
*** IIS
**** Logs
**** Extended IIS Logs
**** FREB
*** .Net
**** WCF
***** SVC Logs
*** EventViewer
*** http.sys
*** External
**** ApplicationInsights

** <&monitor>UI Tools
*** Browser F12
*** Fiddler
*** Wireshark
*** Resource monitor
*** ActiveDirectory
**** Ad Users and Computers
**** AD Domains & trust
**** [[https://docs.microsoft.com/en-us/sysinternals/downloads/adexplorer{Examine the AD} AD Explorer]]
center footer JoymonOnline

legend right
  Left Side - UI Tools
  Right Side - Commands and logs
  <&command>Commands
endlegend

@endmindmap
