@startmindmap
center header
Azure mind maps - Azure Functions
endheader
title Azure - Functions

* <&flag> Functions
caption Azure Functions - Mind Map - Updated on 2020-05-01
center footer JoymonOnline

legend right
  Left Side - Specs, features & theories
  Right Side - Use cases
  
endlegend

@endmindmap