@startmindmap
caption The Unicorn Project - Updated on 2020-03-28
title The Unicorn Project - Mind map
center header
The Unicorn Project
endheader

* <&flag><b>The Unicorn Project</b>
** View of Maxine about development
*** Functional programming
*** Immutable
*** Automated testing
*** CI/CD
*** Dev job completes when customer use feature
*** 2 Pizza teams
*** Environment parity
*** Pay techdebt
**** hard coding
**** Manual prep of env
**** Architecture
*** Dev productivity over features
** [[https://www.linkedin.com/pulse/unicorn-project-five-ideals-michal-florys/ Ideals]]
*** Locality & Simplicity
*** Focus, Flow & Joy
*** Improvement of daily work
*** Psychological safety
**** project oxygen google
*** Customer focus
left side
** RedShirts
*** Maxine Chambers, Developer Lead, Architect
*** Kurt Reznick, QA Manager
*** “Cranky Dave” Brinkley, Developer Lead
*** Shannon Corman, Security Engineer
*** Adam Flynn, QA Engineer
*** Dwayne Cox, Lead Infrastructure Engineer
*** Purna Sathyaraj, QA and Release Manager
*** ➢Brent Geller, Ops Lead
** JUNIOR OFFICERS
*** Randy Keyes, Dev Manager
*** Rick Willis, QA Manager
*** ➢William Mason, Director of QA
*** ➢Wes Davis, Director of Distributed Technology Operations
*** ➢Patty McKee, Director of IT Service Support
** BRIDGE CREW
*** ➢Steve Masters, CEO, Acting CIO
*** ➢Dick Landry, CFO
*** ➢Sarah Moulton, SVP of Retail Operations
*** ➢Chris Allers, VP of Application Development
*** ➢Kirsten Fingle, Director of Project Management
*** ➢Maggie Lee, Senior Director of Retail Program Management
*** ➢Bill Palmer, VP of IT Operations
*** ➢John Pesche, Chief Information Security Officer (CISO)
** STARFLEET COMMAND
*** Alan Perez, New Board Director, Operating Partner, Wayne-Yokohama
*** Equity Partners
*** ➢Bob Strauss, Lead Director, Former Chairman, Former CEO
*** ➢Erik Reid, Prospective Board Director
center footer JoymonOnline

legend right
  Left Side TBD
  Right Side - Terms & definitions
  
endlegend

@endmindmap
