@startmindmap
caption The Unicorn Project - Updated on 2019-10-23
title The Unicorn Project - Mind map
center header
The Unicorn Project
endheader

* <&flag><b>The Unicorn Project</b>
** Ideals
*** Locality
*** Simplicity
*** Improvement of daily work
*** psychological safety
*** Customer focus
left side
** Nothing to put 
center footer JoymonOnline

legend right
  Left Side TBD
  Right Side - Terms & definitions
  
endlegend

@endmindmap
