@startmindmap
caption The Unicorn Project - Updated on 2020-03-28
title The Unicorn Project - Mind map
center header
The Unicorn Project
endheader

* <&flag><b>The Unicorn Project</b>
** View of Maxine about development
*** Functional programming
*** Write Unit test before refactor 
*** Immutable
*** Depoly single change set to production (multi threading fix)
*** Dev job completes when customer use feature
*** Environment parity
*** 2 Pizza teams
*** You build it you run it
*** No ARB/TOGAF
*** Pay techdebt
**** Hard coding
**** Manual prep of env
**** Architecture
*** CI/CD
*** White space deployment
*** Everything in version control
*** Automated testing
*** QA and business colocated with dev
*** Immutable deployment using container
*** independent release of apps 
*** Versioned Microservices
*** Dev productivity over features
*** Blameless post mortem 
**** Release 
**** Outages
*** Taxonomy
*** Code merge 
**** Alteast once a day
**** Without war room
**** Single source repo
**** No extra steps to push from branch to branch(Jared)
*** Chaos engineering
*** Real product experience
*** Feedback loop and experiment with customers
*** Fail fast
** Technologies
*** Kubernetes
*** Clojure
** Names
*** Unicorn - Recommendation system
*** Norva
**** New DB(NoSQL) and API gateway, 
**** Auth, PII anonymization
*** Unikitty - CI/CD System
*** ORCA - Analytics and data science
*** Panther - Modern data warehouse with Spark & event streaming
** [[https://www.linkedin.com/pulse/unicorn-project-five-ideals-michal-florys/ Ideals]]
*** Locality & Simplicity
*** Focus, Flow & Joy
*** Improvement of daily work
*** Psychological safety
**** Project oxygen Google
*** Customer focus
** [[https://medium.com/corporate-ventures/book-review-zone-to-win-by-geoffrey-a-moore-4004f5c7d1da Horizons]]
*** 1 - Core business - Cash cow
*** 2 - Small business - Future cash cow
*** 3 - Innovations - Risky adventures
** Type of teams
*** Core
**** Anything directly bringing revenue from customer eg: Code
*** Context
**** Supporting systems, people. eg: HR, home grown CI/CD system, Email server etc...
left side
** RedShirts
*** Maxine Chambers, Developer Lead, Architect
*** Kurt Reznick, QA Manager
*** “Cranky Dave” Brinkley, Developer Lead
*** Shannon Corman, Security Engineer
*** Adam Flynn, QA Engineer
*** Dwayne Cox, Lead Infrastructure Engineer
*** Purna Sathyaraj, QA and Release Manager
*** ➢Brent Geller, Ops Lead
** JUNIOR OFFICERS
*** Randy Keyes, Dev Manager
*** Rick Willis, QA Manager
*** ➢William Mason, Director of QA
*** ➢Wes Davis, Director of Distributed Technology Operations
*** ➢Patty McKee, Director of IT Service Support
** BRIDGE CREW
*** ➢Steve Masters, CEO, Acting CIO
*** ➢Dick Landry, CFO
*** ➢Sarah Moulton, SVP of Retail Operations
*** ➢Chris Allers, VP of Application Development
*** ➢Kirsten Fingle, Director of Project Management
*** ➢Maggie Lee, Senior Director of Retail Program Management
*** ➢Bill Palmer, VP of IT Operations
*** ➢John Pesche, Chief Information Security Officer (CISO)
** STARFLEET COMMAND
*** Alan Perez, New Board Director, Operating Partner, Wayne-Yokohama
*** Equity Partners
*** ➢Bob Strauss, Lead Director, Former Chairman, Former CEO
*** ➢Erik Reid, Prospective Board Director
center footer JoymonOnline

legend right
  Left Side - Characters
  Right Side - Ideam from the book
  Other links
  - [[https://danlebrero.com/2020/02/05/the-unicorn-project-summary/ DanLebrero]]
  - [[https://www.infoq.com/articles/unicorn-project/ InfoQ]]
endlegend

@endmindmap
