@startmindmap
caption The Phoenix Project - Updated on 2019-10-23
title The Phoenix Project - Mind map
center header
The Phoenix Project
endheader

* <&flag><b>The Phoenix Project</b>
** Types of work
*** BUSINESS
*** Internal
*** Changes
*** Unplanned
** Work center
*** Man
*** Machine
*** Material
*** Measure
** [[https://en.wikipedia.org/wiki/Theory_of_constraints Theory of constraints]]
*** Fix the bottle neck
left side
** Nothing to put 
center footer JoymonOnline

legend right
  Left Side TBD
  Right Side - Terms & definitions
  
endlegend

@endmindmap
