@startmindmap
center header
Mind map on Gen AI for developers 
endheader
title GenAI Landscape for app developers
*: <&flag> GenAI 
App Dev;
left side
** Platform
*** Onpremise
****_ [[https://ollama.com/ Ollama]]
*** Cloud
****_ Azure OpenAI
****_ AWS Bedrock
****_ GCP Vertex AI
** Orchestration
***_ LangChain
***_ Haystack
***_ Auto-GPT
***_ LlamaIndex
** Apps
*** Text
****_ ChatGPT
****_ Gemini
****_ Claude
*** Images
****_ MidJourney
****_ DALL-E
*** Coding
****_ GH CoPilot
****_ AWS CodeWhisper
*** Automation
****_ AutoGPT
****_ AutoChain
****_ WorkGPT

right side
** Infra/hardware
***_ nVidea
***_ CoreWeave
*** Cloud IaaS
** Models
*** Hubs
****_ HuggingFace
****_ [[https://replicate.com/ Replicate]]
****_ [[https://openwebui.com/ Ollama Hub]]
*** Types
**** 🗎Text
*****_:GPT by OpenAI
3.5 Turbo, 4 turbo, 4o, 4o mini;
*****_: Claude by Anthropic
 3 Sonnet/Haiku/Opus,
 3.5 Sonnet;
*****_: <:book:> Llama by Meta
3.1 405B, 70B, 8B ;
*****_: PaLM2 by Google
;
**** Images
*****_ DALL-E by OpenAI
**** 🔊Audio
**** 📹Video
**** Multimodal
*****_: Gemini by Google
1.0 Nano, Flash,1.5 Pro, 1.0 Ultra;
** Patters
*** Fine-tuning
*** RAG
**** External data sources
*****_ Vector indexes

legend right
# <:cloud:> - Cloud hosted
# <:book:> - Opensource
# Platform - runs the Models.
# Apps are listed for understanding, not all.
# [[https://www.stork.ai/ Stork Tools list]]
# [[https://platform.openai.com/docs/models/models-overview Full OpenAI Models]]
endlegend

caption GenAI - Developer mind map © Joy George Kunjikkuru

@endmindmap