@startmindmap
center header
Lang Chain
endheader
title LangChain mind map
* <&flag> LangChain
left side
** Prompts
**[#Orange] Chains
**_ when to use
***_ Prompt templates
***_ Document Retrieval
***_ Conversation memory
***_ Tool call
***_ Complex WFs
right side
** Indexes
***_ DocumentLoader
***_ VectorDB
***_ TextSplitting
**: LLMs 
;
** Memory
** Agents

legend right
# mm does not support notes

endlegend

caption LangChain MindMap

@endmindmap