@startmindmap
center header
Software tools - I am using
endheader
title Software technologies, tools and utilities - Personal Use
caption Software technologies, tools and utilities - Mind Map - Updated on 2020-05-17
center footer JoymonOnline
* <&flag> Software
** Design
*** Diagrams - [[https://en.wikipedia.org/wiki/PlantUML PlantUML]] - ([[https://www.youtube.com/watch?v=Zt3Bj1HMJ8g Set up video]])
*** Documentation - [[https://en.wikipedia.org/wiki/Markdown Markdown]]
** Technologies
*** Scripting
**** PowerShell
*** Container
**** Docker
*** Automation / NoCode
**** [[https://zapier.com/home Zapier]] & [[https://gist.github.com/joymon/89aeb18bef588895426b46a54e2ba970 others]]
*** Visualization
**** Power BI
** IDE/Editor
*** [[https://code.visualstudio.com/ VS Code]]
*** [[https://notepad-plus-plus.org/ Notepad++]]

** Media
*** Photos
**** Screenshot - Snipper
**** Vector
***** Editing
****** Desktop [[https://inkscape.org/ Inkspace]]
****** Online [[https://vectr.com/ Vectr]]
***** Stock 
****** [[https://www.vectorstock.com/ VectorStock.com]]
**** Raster photos
***** Desktop - [[https://www.getpaint.net/ Paint.Net]]
***** Online - [[https://www.photopea.com/ PhotoPea]]
**** Design
***** Spark, [[https://snappa.com/ Snappa]], [[https://www.canva.com/ Canva]], [[https://www.befunky.com/ Befunky]]
***** Converters
****** [[https://gifrun.com/ YouTube To GIF]]
*** Video
**** Player - [[https://www.videolan.org/vlc/download-windows.html VLC]]
**** [[https://www.plantuml.com/plantuml/proxy?fmt=svg&cache=no&src=https://raw.githubusercontent.com/mind-maps/technology/master/media/video/publishing.puml Production]]
*** Audio
**** Record, edit, noise removal - [[https://www.audacityteam.org/download/ Audacity]]

left side

**_ Task management
*** [[https://trello.com/ Trello]]
** System
*** OS
**** Windows 10
***** [[https://github.com/joymon/win10-dev-box-setup Environment setup]]
****** Choco+PowerShell
***** [[https://www.av-test.org/en/antivirus/home-windows/ Antivirus]]
****** Window defender
****** [[https://www.avg.com/ Avg]]
*** Partitioning - [[https://www.diskpart.com/free-partition-manager.html AOMEI]]
*** [[http://www.emptyloop.com/unlocker/ Unlocker]]
** Files
*** Clean
**** Find duplicate
***** [[http://www.alldup.info/en_download_alldup.php AllDup]]
**** Cleaner
***** [[https://www.ccleaner.com/ CClearer]]
*** Compare
**** [[https://winmerge.org/?lang=en WinMerge]]
*** Sync
**** [[https://www.microsoft.com/en-us/download/details.aspx?id=15155 SyncToy]](Windows)
*** Cloud storage
**** GDrive, OneDrive
** Office
*** Google Docs, Sheets
*** Presentation slides
**** [[https://revealjs.com/ RevealJS]] + [[https://marketplace.visualstudio.com/items?itemName=evilz.vscode-reveal VSCode Ext]]
*** [[https://www.onenote.com/ One Note]]
*** Editing
**** [[https://app.grammarly.com/ Grammarly]]
** Publishing
*** Video
**** YouTube
***** [[https://www.youtube.com/channel/UC78wYrq_keVaDV8STReHRxg Joymon v/s Code]]
***** [[https://www.youtube.com/channel/UCzYqSifCwLYpmgRxvNo7BzA The J3D Family]]
***** [[https://www.youtube.com/channel/UC1D3Fy0L0aoI0OfUEZnWy5A Johan & Jerin Playtime]]
*** Blog
**** Blogger
***** [[https://joymonscode.blogspot.com/ Joymon v/s Code]]
***** [[https://joy-mon.blogspot.com/ എന്‍റെ ബ്ലോഗാന്വേഷണ പരീക്ഷണങ്ങള്‍]] ([[https://en.wikipedia.org/wiki/Malayalam Malayalam language]])

legend right
All the tools are free, mostly open source. Except Win 10
Left Side - Tools used for infrastructure and environment
Right Side - Tools for personal projects
[[https://joymonscode.blogspot.com/2017/05/toolbox-for-open-source-developers.html Old plain list]]
  
endlegend

@endmindmap
