@startmindmap
center header
Software tools - I am using for personal Software engineering
endheader
title Software technologies, tools and utilities - Personal projects
caption Software technologies, tools and utilities - Mind Map - Updated on 2020-05-17
center footer JoymonOnline
* <&flag> Software
** Make Money
*** [[Algorithmia.com Algorithmia]]
*** [[https://www.chargebee.com/pricing Chargebee]]
** Testing
*** Unit
**** MS Test, Jasmine,
*** e2e
**** Jest, Puppeteer
*** Load
**** [[http://blazemeter.com Blaze meter]]

** Cheatsheets
*** [[https://dzone.com/refcardz DZone]], [[http://www.cheat-sheets.org/ Cheat-sheets]],[[https://www.cheatography.com/ Cheatography]]
** Public APIs
*** [[https://www.programmableweb.com/ ProgrammableWeb]],[[https://any-api.com/ any-api]],[[https://apis.guru/browse-apis/ apis.guru]], [[http://www.apiforthat.com/ apisforthat]]
** SaaS
*** Mail - [[https://mailchimp.com/ mailchimp]]
*** SMS ??
** Find vendors and third parties
*** [[https://www.getapp.com/ GetApp.com]]
*** [[https://www.whatasoftware.com/ Whatasoftware]]
*** [[https://stackshare.io/ stackshare]]
*** [[https://www.slant.co/ Slant.co]]
** Hosted tools
*** RegEx
*** [[https://countwordsfree.com/text-encode Html & Url encode and decode]]
*** [[https://jwt.io JSON Web Token tester]]
*** [[https://countwordsfree.com/jsonviewer JSON & XML Formatters]]
** Debugging
*** .Net Code 
**** WinDbg, DebugDiag 
*** Performance
**** Perfview
*** Network
**** Remote desktop connection manager
**** [[http://www.plantuml.com/plantuml/proxy?fmt=svg&cache=no&src=https://raw.githubusercontent.com/mind*maps/software/master/debugging/windows*network*debugging.puml Network tools & cmds]]
*** Decompile .Net - [[https://www.telerik.com/products/decompiler.aspx JustDecompile]]
*** System
**** [[https://docs.microsoft.com/en-us/sysinternals/ SysInternals]]
*** Logs - Logparser Studio

** Files
*** Compare - WinMerge
*** Unlocker

left side

** Design
*** Diagrams
**** PlantUML
**** Online
***** [[https://lucid.app Lucid Charts]]
***** [[https://creately.com Creately]]
*** Documentation - Markdown
** Technologies
*** [[https://forms.microsoft.com/ Forms, surveys, polls]]
*** Automation / NoCode
**** [[https://zapier.com/home Zapier]] & [[https://gist.github.com/joymon/89aeb18bef588895426b46a54e2ba970 others]]
*** Visualization
**** Power BI
*** Scripting
**** PowerShell
*** Container
**** Docker
*** Full application
**** NodeJS + NPM
**** ASP.Net Core + Nuget

** DevOps
*** Source control, tasks,issues - GitHub
*** CI/CD
**** GitHub Actions
**** Previous
***** AppVeyor
***** TravisCI
** IDE/Editor
*** Notepad++
*** Visual Studio
**** Code
**** 2019 Community

** Hosting
*** Domain - GoDaddy (paid)
*** Static site
**** GitHub Pages
*** APIs
**** Azure App Service, Functions
**** [[https://firebase.google.com/pricing Firebase]]
**** WebTask.io
** Monitoring
*** Ping
**** Uptime check
***** [[https://uptimerobot.com/pricing UptimeRobot]]

*** Hosted Log Aggregator
**** [[https://www.loggly.com/plans-and-pricing/ Loggly]]
**** [[https://www.papertrail.com/plans/ Papertrail]]
**** [[https://sentry.io/pricing/ Sentry]]
**** [[https://rollbar.com/pricing/ Rollbar]]
**** [[https://www.bugsnag.com/pricing Bugsnag]]
**** [[https://github.com/cheeaun/javascript-error-logging More]]
legend right
All the tools are free, mostly open source.
Left Side - Tools used for software development 
Right Side - Debugging & Misc tools
[[https://joymonscode.blogspot.com/2017/05/toolbox-for-open-source-developers.html Old plain list]]
  
endlegend
@endmindmap