@startmindmap
center header
Software tools - I am using
endheader
title Software technologies, tools and utilities
caption Software technologies, tools and utilities - Mind Map - Updated on 2020-05-17
center footer JoymonOnline
+ <&flag> Software
++ Task management - Trello
++ Automation / NoCode
+++ [[https://zapier.com/home Zapier]] & [[https://gist.github.com/joymon/89aeb18bef588895426b46a54e2ba970 others]]
++ Media
+++ Photos
++++ Snapshot - Snipper
++++ Editing
+++++ Desktop - Paint.Net
+++++ Online - [[https://www.photopea.com/ PhotoPea]]
++++ Design
+++++ Spark, Snappa, Canva
+++ Video
++++ Player - VLC
++++ Production
+++++ Editor - Shotcut
+++++ Cut and merge - LosslessCut
+++++ Screen cast - ActivePresenter
+++ Audio
++++ Audacity
++ Files
+++ Clean
++++ Find duplicate - AllDup
++++ Cleaner - CClearer
+++ Compare - WinMerge
+++ Cloud storage
++++ GDrive, OneDrive
++ Office
+++ Google Docs, Sheets
+++ One Note
+++ Editing
++++ Grammarly
+++ Visualization
++++ Power BI
++ System
+++ Antivirus
++++ Window defender
++++ Avg
+++ Partitioning - [[https://www.diskpart.com/free-partition-manager.html AOMEI]]
+++ Unlocker
-- Design
--- Diagrams - PlantUML
--- Documentation - Markdown
-- Technologies
--- NodeJS + NPM
--- ASP.Net Core + Nuget
-- Scripting
--- PowerShell
-- IDE/Editor
--- Visual Studio 2019
--- VS Code
--- Notepad++
-- Container
--- Docker
-- DevOps
--- Source control - GitHub
--- CI/CD
---- AppVeyor
---- TravisCI
-- Hosting
--- Domain - GoDaddy (paid)
--- Static site
---- GitHub Pages
--- APIs
---- Azure App Service, Functions
---- [[https://firebase.google.com/pricing Firebase]]
---- WebTask.io
-- Debugging
--- .Net Code
---- WinDbg, DebugDiag
--- Performance
---- Perfview
--- Network
---- Remote desktop connection manager
---- [[http://www.plantuml.com/plantuml/proxy?fmt=svg&cache=no&src=https://raw.githubusercontent.com/mind-maps/software/master/debugging/windows-network-debugging.puml Network tools & cmds]]
--- Decompile .Net - [[https://www.telerik.com/products/decompiler.aspx JustDecompile]]
--- System
---- [[https://docs.microsoft.com/en-us/sysinternals/ SysInternals]]
--- Logs - Logparser Studio

legend right
All the tools are free, mostly open source.
Left Side - Tools used for software development and debugging
Right Side - Misc tools for personal and work
[[https://joymonscode.blogspot.com/2017/05/toolbox-for-open-source-developers.html Old plain list]]
  
endlegend

@endmindmap