@startmindmap
center header
Software tools - I am using
endheader
title Software technologies, tools and utilities
caption Software technologies, tools and utilities - Mind Map - Updated on 2020-05-17
center footer JoymonOnline
+ <&flag> Software
++ Media
+++ Photos
++++ Editing
+++++ Desktop - Paint.Net
+++++ Online - [[https://www.photopea.com/ PhotoPea]]
+++ Video
++++ Player - VLC
++++ Editing
+++++ Editor - Shotcut
+++++ Cut and merge - LosslessCut
+++ Audio
++++ Audacity
++ Files
+++ Find duplicate - AllDup
+++ Cleaner - CClearer
+++ Compare - WinMerge
+++ Cloud storage
++++ GDrive, OneDrive
++ Office
+++ Google Docs, Sheets
+++ One Note
++ System
+++ Antivirus
++++ Window defender
++++ Avg
+++ Partitioning
-- Debugging
--- [[http://www.plantuml.com/plantuml/proxy?fmt=svg&cache=no&src=https://raw.githubusercontent.com/mind-maps/software/master/debugging/windows-network-debugging.puml Network]]
-- IDE/Editor
--- Visual Studio 2019
--- VS Code
--- Notepad++
-- Technologies
--- NodeJS
--- ASP.Net Core
-- Scripting
--- PowerShell

legend right
All the tools are free, mostly open source.
Left Side - Tools used for software development and debugging
Right Side - Misc tools good for personal and work
  
endlegend

@endmindmap