@startuml
@startmindmap
caption Mind map of SQL Server performance considerations
title Mind map on SQL Server Web Performance
center header
SQL Server Web Performance
endheader

center footer JoymonOnline
* <&flag><b>SQL-Performance</b>
** Client app
*** Cache
**** Metadata to reduce calls
**** Data for short time
*** Background jobs
** <&globe>TSQL
*** DDL
**** Triggers
**** Indexes
**** In-memory table
*** DML
**** Select *
**** Filter rows
**** udf calls
**** like %%
**** Dynamic objects
*** Cursor 
*** re-compile
** Waits
** Memory
*** Page lift expectancy
left side

** <&globe>Setup & Infra
*** Connectivity
**** Bandwidth with clients
**** Protocol
*** Storage
**** Temp db file location
**** Partitioning
**** File growth
*** [[https://docs.microsoft.com/en-us/sql/t-sql/database-console-commands/dbcc-traceon-trace-flags-transact-sql?view=sql-server-2017 Flags]] 
*** HA & DR
**** Always On HighAvailability
***** Connectivity <-> replica
**** SQL FCI + LogShipping
*** Index maintenance
*** Azure SQL VM Considerations
** Tools & monitoring
*** SQL
**** Log data points
***** [[https://docs.microsoft.com/en-us/archive/blogs/psssql/sql-server-correlating-timestamps-from-various-data-points Correlating timestamps]]
**** SQL Profiler
**** Extended Events
**** [[https://www.sqlshack.com/sql-server-query-store-overview/ Query Store]]
**** Reports
**** PSSDiag
*** OS
**** Perfmon
**** Resource monitor
legend right
  Left Side - SQL Server setup, maintenance
  Right Side - Databases and applications
   
endlegend
@endmindmap
@enduml