@startuml
@startmindmap
caption Mind map of SQL Server performance considerations
title Mind map on SQL Server Web Performance
center header
SQL Server Web Performance
endheader

center footer JoymonOnline
* <&flag><b>SQL-Performance</b>
** Client app
*** Cache
**** Metadata to reduce calls
**** Data for short time
** <&globe>TSQL
*** DDL
**** Triggers
**** Indexes
**** In-memory table
*** DML
**** Select *
**** Filter rows
**** like %%
*** Cursor
*** re-compile

left side

** <&globe>Setup & Infra
*** Connectivity
**** Bandwidth with client
*** Storage
**** Temp db file location
**** Partitioning
**** File growth
*** [[https://docs.microsoft.com/en-us/sql/t-sql/database-console-commands/dbcc-traceon-trace-flags-transact-sql?view=sql-server-2017 Flags]] 
*** HA & DR
**** Always On HighAvailability
***** Connectivity <-> replica
*** Index maintenance
*** Azure SQL VM Considerations

legend right
  Left Side - SQL Server setup, maintenance
  Right Side - Databases and applications
   
endlegend
@endmindmap
@enduml